language: java

services:
  - postgresql

notifications:
  email:
    recipients:
      - ephemeralin@gmail.com
    on_success: always # default: change
    on_failure: always # default: always

before_install:
  - postgresql -e 'CREATE DATABASE SIREN;'
#  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('6EgM3zX6EE') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"

before_script:
  - echo "USE mysql; UPDATE user SET password=PASSWORD('6EgM3zX6EE') WHERE user='root';FLUSH PRIVILEGES;" | mysql -u root

after_success:
  - bash <(curl -s https://codecov.io/bash)
